package dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import dao.UserDbDao;
import dao.GroupDbDao;
import dao.ApiDbDao;
import dao.ProjectDbDao;
import dao.LateCollectionDbDao;
import dao.JoinDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 2): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 2;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        UserDbDao.createTable(db, ifNotExists);
        GroupDbDao.createTable(db, ifNotExists);
        ApiDbDao.createTable(db, ifNotExists);
        ProjectDbDao.createTable(db, ifNotExists);
        LateCollectionDbDao.createTable(db, ifNotExists);
        JoinDbDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        UserDbDao.dropTable(db, ifExists);
        GroupDbDao.dropTable(db, ifExists);
        ApiDbDao.dropTable(db, ifExists);
        ProjectDbDao.dropTable(db, ifExists);
        LateCollectionDbDao.dropTable(db, ifExists);
        JoinDbDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(UserDbDao.class);
        registerDaoClass(GroupDbDao.class);
        registerDaoClass(ApiDbDao.class);
        registerDaoClass(ProjectDbDao.class);
        registerDaoClass(LateCollectionDbDao.class);
        registerDaoClass(JoinDbDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
