package bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "API_DB".
 */
public class ApiDb {

    private Long id;
    private String pid;
    private Integer gid;
    private String aid;
    private String url;
    private Integer deployStatus;
    private String name;
    private String description;
    private String urlsuffix;
    private String method;
    private Integer ability;
    private String output;
    private Integer status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ApiDb() {
    }

    public ApiDb(Long id) {
        this.id = id;
    }

    public ApiDb(Long id, String pid, Integer gid, String aid, String url, Integer deployStatus, String name, String description, String urlsuffix, String method, Integer ability, String output, Integer status) {
        this.id = id;
        this.pid = pid;
        this.gid = gid;
        this.aid = aid;
        this.url = url;
        this.deployStatus = deployStatus;
        this.name = name;
        this.description = description;
        this.urlsuffix = urlsuffix;
        this.method = method;
        this.ability = ability;
        this.output = output;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPid() {
        return pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }

    public Integer getGid() {
        return gid;
    }

    public void setGid(Integer gid) {
        this.gid = gid;
    }

    public String getAid() {
        return aid;
    }

    public void setAid(String aid) {
        this.aid = aid;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getDeployStatus() {
        return deployStatus;
    }

    public void setDeployStatus(Integer deployStatus) {
        this.deployStatus = deployStatus;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getUrlsuffix() {
        return urlsuffix;
    }

    public void setUrlsuffix(String urlsuffix) {
        this.urlsuffix = urlsuffix;
    }

    public String getMethod() {
        return method;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public Integer getAbility() {
        return ability;
    }

    public void setAbility(Integer ability) {
        this.ability = ability;
    }

    public String getOutput() {
        return output;
    }

    public void setOutput(String output) {
        this.output = output;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
