package bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PROJECT_DB".
 */
public class ProjectDb {

    private Long id;
    private String pid;
    private String name;
    private String info;
    private String desc;
    private String urlprefix;
    private Integer status;
    private Integer authorStatus;
    private String virtualUrl;
    private String author;
    private Integer authority;
    private String username;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ProjectDb() {
    }

    public ProjectDb(Long id) {
        this.id = id;
    }

    public ProjectDb(Long id, String pid, String name, String info, String desc, String urlprefix, Integer status, Integer authorStatus, String virtualUrl, String author, Integer authority, String username) {
        this.id = id;
        this.pid = pid;
        this.name = name;
        this.info = info;
        this.desc = desc;
        this.urlprefix = urlprefix;
        this.status = status;
        this.authorStatus = authorStatus;
        this.virtualUrl = virtualUrl;
        this.author = author;
        this.authority = authority;
        this.username = username;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPid() {
        return pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getUrlprefix() {
        return urlprefix;
    }

    public void setUrlprefix(String urlprefix) {
        this.urlprefix = urlprefix;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getAuthorStatus() {
        return authorStatus;
    }

    public void setAuthorStatus(Integer authorStatus) {
        this.authorStatus = authorStatus;
    }

    public String getVirtualUrl() {
        return virtualUrl;
    }

    public void setVirtualUrl(String virtualUrl) {
        this.virtualUrl = virtualUrl;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public Integer getAuthority() {
        return authority;
    }

    public void setAuthority(Integer authority) {
        this.authority = authority;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
