package bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "USER_DB".
 */
public class UserDb {

    private Long id;
    private String username;
    private String pwd;
    private String date;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UserDb() {
    }

    public UserDb(Long id) {
        this.id = id;
    }

    public UserDb(Long id, String username, String pwd, String date) {
        this.id = id;
        this.username = username;
        this.pwd = pwd;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPwd() {
        return pwd;
    }

    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
